name: http
version: 0.13.0-nullsafety.0
homepage: https://github.com/dart-lang/http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.3
  path: ^1.8.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety
  charcode: ^1.2.0-nullsafety
  collection: ^1.15.0-nullsafety.2
  source_span: ^1.8.0-nullsafety
  string_scanner: ^1.1.0-nullsafety
  typed_data: ^1.3.0-nullsafety.2

dev_dependencies:
  test: ^1.16.0-nullsafety.4

dependency_overrides:
  # Because pkg:test does not support pkg:http ^0.13.0
  test: ^1.16.0-nullsafety.5
  shelf: 0.7.9
  shelf_static: 0.2.8
